#baseURL = 'https://d-austen.github.io/stumeta2025-website'
baseURL = '/' #use this when opening from public folder, still need to adjust paths
relativeURLs = true
uglyURLs = true
languageCode = 'en-us'
title = 'My New Hugo Site'
disableKinds = ['taxonomy', 'term']
logo = 'static/img/Stumeta-logo1.jpg'


[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/sass/bootstrap"

  [[module.mounts]]
source = "assets"
target = "assets"
